# compose.yaml
services:
  floci:
    image: floci/floci:latest
    ports:
      - "4566:4566"
    environment:
      - FLOCI_STORAGE_MODE=hybrid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # necessário se for usar Lambda, RDS, ECS etc.